destination: ./_site
server: true
auto: true
lsi: false
pygments: false
markdown: maruku
permalink: pretty
maruku:
    use_tex: false
    use_divs: false
    png_dir: /images/latex
    png_url: /images/latex
